### ISSUE TITLE
iPhone shuttles map animation bug

### ISSUE THREAD

**Issue by rosslebeau** [MIT-Mobile/MIT-Mobile-for-iOS#791]
When going from full-screen map to half-screen, the bottom half of the screen (with stops/predictions) sometimes animates all the way to the nav bar before snapping back to below the map.

**Comment by rosslebeau** [comment]
@justinanderson Should be fixed in master - idk if you need to review since I posted the bug, but you should be able to switch from full-screen map to half-screen and back on iPhone now and never get this animation glitch (or any others AFAIK).

**Comment by Smartcop** [comment]
@rosslebeau 
Still happens but rarely.  Trying to figure out what I am doing to get it to replicate.

**Comment by rosslebeau** [comment]
@Smartcop Ok thanks. My fix was only aimed at the RouteViewController, since I was pretty sure the issue didn't extend to when you were viewing the StopViewController...if you are seeing this when viewing the StopViewController, then it's probably a quick fix for me to add.

The issue stemmed from reloading the tableview when the RouteContainerViewController was in fullscreen map mode. This was triggered from a returning web call, so perhaps you can reproduce it simply by waiting ~10-60 seconds for the predictions or vehicles calls to return?

**Comment by Smartcop** [comment]
:+1: Rarely happens now compared to before.  I probably have been hitting it when the above (you mentioned) happens.
